### ISSUE TITLE
react-todo-list

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [xgqfrms-GitHub/React-Redux-Todo-List#1]
http://todomvc.com/examples/react/#/

https://github.com/xgqfrms-GitHub/Node-CLI-Tools/wiki/react-todo-list

**Comment by xgqfrms-GitHub** [comment]
```js
{
    "name": "react-redux-todo-list",
    "version": "1.1.1",
    "private": true,
    "bin": {
        "rrtl": "rrtlcli"
    },
    "scripts": {
        "rrtl": "node rrtlcli",
        "start": "node rrtlcli"
    },
    "dependencies": {
        "colors": "^1.1.2",
        "node-fetch": "^1.7.1"
    }
}

```

**Comment by xgqfrms-GitHub** [comment]
```yaml
language: node_js
node:
- 6.10.3
npm:
- 5.0.2
os:
- windows10 x64 pro
```
